### ISSUE TITLE
My program isn't running and the emulator thinks i dont have python

### ISSUE THREAD

**Issue by takashiti** [mattbatwings/BatPU-2#17]
This is my first program so I don't know if I'm doing something wrong.

LDI r1 5
LDI r2 1
ADI r1 r2 r1
ADD r1 r1 r2
ADD r1 r2 r3
ADD r1 r3 r2

**Comment by mattbatwings** [comment]
Please move this issue to the emulator repo https://github.com/AdoHTQ/Batpu2-VM/releases
