### ISSUE TITLE
Blocks dissapear

### ISSUE THREAD

**Issue by BubblePlayzTHEREAL** [mattbatwings/BatPU-2#20]
Before
![image](https://github.com/user-attachments/assets/a2f67296-dfbc-448f-ba2a-e6b7e63d3cd9)

After
![image](https://github.com/user-attachments/assets/c8739f8c-b35d-4371-9c4a-970174cfcfc1)

**Comment by BubblePlayzTHEREAL** [comment]
Nevermind, I ran the wrong command

**Comment by mattbatwings** [comment]
also if this is on mchprs then make sure to paste the program before u transfer the schem
