### ISSUE TITLE
Bytes in the Instruction Memory are in the wrong order.

### ISSUE THREAD

**Issue by MatthewFrieri** [mattbatwings/BatPU-2#23]
In schematic.py lines 45-46:

byte1 = line[8:]
byte2 = line[:8]

This is incorrectly mapping the machine code to minecraft repeaters, causing programs to not run as described in the latest video EP 5.
Not sure if this is something that's later addressed by changing the minecraft wiring.

If not, the correct mapping should look like this:

byte1 = line[:8]
byte2 = line[8:]

**Comment by mattbatwings** [comment]
This assembler is for the final build only, which you can download on the README of this repo.
